# Generated by Buildr 1.4.9, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "restq"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"
repositories.remote << 'http://artifactory.nm.flipkart.com:8081/artifactory/libs-releases'
repositories.remote << 'http://artifactory.nm.flipkart.com:8081/artifactory/libs-snapshots-local'

NETTY = 'io.netty:netty:jar:3.5.10.Final'
REST_EXPRESS = [
	'RestExpress:RestExpress:jar:0.8.1.patched', 'DateAdapterJ:DateAdapterJ:jar:1.1.0', 
	'com.google.code.gson:gson:jar:2.2.2',
	'com.thoughtworks.xstream:xstream:jar:1.4.2',
	'xmlpull:xmlpull:jar:1.1.3.1'
	]
SLF4J = 'org.slf4j:slf4j-log4j12:jar:1.6.6'
MOCKITO = 'org.mockito:mockito-all:jar:1.9.0'

desc "The Restq project"
define "restq" do
  eclipse.natures ['org.eclipse.jdt.core.javanature', 'org.eclipse.jem.workbench.JavaEMFNature', 'org.eclipse.wst.common.modulecore.ModuleCoreNature', 'org.eclipse.wst.common.project.facet.core.nature', 'org.eclipse.wst.jsdt.core.jsNature']
  eclipse.builders ['org.eclipse.wst.jsdt.core.javascriptValidator', 'org.eclipse.jdt.core.javabuilder', 'org.eclipse.wst.common.project.facet.core.builder', 'org.eclipse.wst.validation.validationbuilder']
  eclipse.classpath_containers ['org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.6']

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  compile.with transitive(NETTY), REST_EXPRESS, transitive(SLF4J)
  test.using :testng
  test.with MOCKITO
end
